name: fisi2028
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - configparser
  - cryptography
  - cython
  - decorator
  - emoji
  - graphite2
  - graphviz
  - h5py
  - hdf5
  - imageio
  - imagemagick
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - jupyterlab_launcher
  - keras-applications
  - keras-preprocessing
  - kiwisolver
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mpmath
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - nltk
  - notebook
  - numba
  - numpy
  - pandas
  - pandoc
  - pandocfilters
  - pip
  - progressbar2
  - pycountry
  - pycparser
  - pytest
  - pytest-runner
  - python=3
  - python-dateutil
  - python-utils
  - python_abi
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - sympy
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - tqdm
  - traitlets
  - tweepy
  - unicodedata2
  - vdom
  - vegasflow
  - widgetsnbextension
  - wordcloud
